### ISSUE TITLE
This test will always pass, if the 'new_mail_post' function does not work, the test will still pass

### ISSUE THREAD

**Issue by adbeskine** [HVLLOWe3n/TDD-Blog-Example#1]
https://github.com/HVLLOWe3n/TDD-Blog-Example/blob/68c6c528e30693c5d2d5edb34d54db8cd7955457/blog/tests.py#L41

in the setup, a post object is created in the database with the author 'roman'. In the test you are trying to create a post object with the author 'roman'. If the 'new_mail' fails and does not create a new post, the assert will find the original post object and the test will pass.

https://docs.djangoproject.com/en/dev/ref/models/querysets/#django.db.models.query.QuerySet.exists

**Comment by HVLLOWe3n** [comment]
Okay, I saw the problem, a really significant problem, thanks for the comment, I'm already working on a solution, expect new commits!

**Comment by HVLLOWe3n** [comment]
https://github.com/HVLLOWe3n/TDD-Blog-Example/commit/2349adc1d7a0def98a4dc279c6a01b84b033b09f

Problem solved!

**Comment by adbeskine** [comment]
great
